presets:
  Hype_Default:
    big_trade_usd: 250000
    dynamic: true
    lookback_news: 24
    max_assets: 100
    min_notional: 300000.0
    strategy: Hype
    threshold: 70
    vol_z_threshold: 1.5
  Quant_Strict:
    big_trade_usd: 250000
    dynamic: true
    lookback_news: 24
    max_assets: 120
    min_notional: 400000.0
    strategy: Quant
    threshold: 75
    vol_z_threshold: 1.0
  Whale_Loose:
    big_trade_usd: 200000
    dynamic: true
    lookback_news: 24
    max_assets: 120
    min_notional: 300000.0
    strategy: Whale
    threshold: 70
    vol_z_threshold: 1.2
